
TYPE
	LogBooksType : 	STRUCT 
		Ident : ARRAY[0..LOGBOOK_BOOKS_MAX]OF UDINT;
		RecordIDLatest : ARRAY[0..LOGBOOK_BOOKS_MAX]OF UDINT;
		RecordIDOld : ARRAY[0..LOGBOOK_BOOKS_MAX]OF UDINT;
		RecordIDIsLast : ARRAY[0..LOGBOOK_BOOKS_MAX]OF BOOL;
		RecordID : ARRAY[0..LOGBOOK_BOOKS_MAX]OF UDINT;
		CntLogbook : USINT;
	END_STRUCT;
END_TYPE
